name: Create Go Package

on:
  workflow_dispatch:

jobs:
  create_go_package_and_push:
    name: Create Go package and push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Zip Go files
        run: |
          zip -r ../go.zip go

      - name: Define global config git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-action@users.noreply.github.com"

      - name: Create new branch from main
        run: |
          git checkout -b feature/go-pr_${{ github.event.pull_request.number }}-${{ github.event.created_at }}
          git push -u origin feature/go-pr_${{ github.event.pull_request.number }}-${{ github.event.created_at }}

      - name: Move zip Go file to workspace
        run: |
          mv ../go.zip .

      - name: Push zip Go file to new branch
        run: |
          git add go.zip
          git commit -m "Added new Go package: '${{ github.event.pull_request.title }}'"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: Update Go Package
            title: ${{ github.event.pull_request.title }}
            body: ${{ github.event.pull_request.body }}
            base: main
            branch: feature/go-pr_${{ github.event.pull_request.number }}-${{ github.event.created_at }}
            delete-branch: true


